### ISSUE TITLE
how to open at 4.10?

### ISSUE THREAD

**Issue by leegod** [AndrewScheidecker/BrickGame#13]
I got this error when try to open this project at 4.10

![error](https://cloud.githubusercontent.com/assets/6247030/10711061/845e1e88-7aab-11e5-8ac3-c513debdc223.PNG)

**Comment by AndrewScheidecker** [comment]
Thanks for the report. I'll investigate this once 4.10 is released.

**Comment by AndrewScheidecker** [comment]
I never reproduced this myself, but I updated the BrickGame engine fork and BrickGame to 4.11, and everything seems to work so I'm closing this for now.
