### ISSUE TITLE
Safe to call GetScene() in FFunctionGraphTask?

### ISSUE THREAD

**Issue by majicalhack** [AndrewScheidecker/BrickGame#14]
Thanks for the awesome code!

I was having stability issues around the GetScene() calls in the FFunctionGraphTask::CreateAndDispatchWhenReady lambda in the BrickRenderComponent.cpp code (lines 496 and 502). I asserted the GetScene() and it was occasionally returning nullptr there. I moved the GetScene()->GetFeatureLevel() call to before the CreateAndDispatchWhenReady block and saved the result to a variable and used that in the CreateAndDispatchWhenReady block instead. This apparently fixed the issue. Thanks!

**Comment by AndrewScheidecker** [comment]
You're right that it's not safe to call GetScene from other threads. I'll make this change next time I'm working on BrickGame. Thanks!

**Comment by majicalhack** [comment]
Great, thanks for the confirmation!

**Comment by AndrewScheidecker** [comment]
[Fixed](https://github.com/AndrewScheidecker/BrickGame/commit/52b4055cb7633cd5dcd45979876a633f6c676782)
