### ISSUE TITLE
Terrain Modification values?

### ISSUE THREAD

**Issue by iUltimateLP** [AndrewScheidecker/BrickGame#18]
Hi, I found out what some values do by modifying them, but I still have some questions relating to the different values. Could you please explain what some of the values like **Uneroded Height** do, and what Lacunarity and the period does? I want to modify the values so a big beautiful meadow comes out, but it seems like I'm not getting the values right. Could you help me? :)

Thanks :+1:

**Comment by Ryvar** [comment]
Ctrl+C the contents of this PasteBin link, right-click on "Terrain Generation Parameters", and select paste. It's not perfectly flat but should give you a good indication as to how to go (reduce max values on uneroded/eroded to flatten, up moisture to reduce sandy patches): http://pastebin.com/PcsSvGNu

Caveat: these values are from a slightly outdated build of BrickGrid (should still work), and it's possible they'll zero out your Dirt Thickness/Cavern Threshold curve parameters, so double-check that hasn't happened before you hit Play/Simulate.

**Comment by iUltimateLP** [comment]
Oh thanks, that looks really nice! If you use stone as the grass material, it looks like the moon :joy: One question, is it possible to create a multi-biome world? I mean, with just one BrickGrid? I would need to do a lot of changes to the BrickGrid plugin as I think, but would that maybe a nice feature?
