### ISSUE TITLE
UnrealEngine 4.10.3

### ISSUE THREAD

**Issue by ninjanody** [AndrewScheidecker/BrickGame#19]
Hello,

When trying to open the project it ask to select engine with the following option in the dropdown:
- 4.10
- UnrearTournament from Source

If i select 4.10 it throws the first error and if i try to rebuild them the second.
![missing-modules](https://cloud.githubusercontent.com/assets/8069158/13640059/0ffee54a-e61c-11e5-8fcb-41209441ba31.png)
![missing-modules-error](https://cloud.githubusercontent.com/assets/8069158/13640069/13111730-e61c-11e5-8be6-670c50dfe949.png)

**Comment by iUltimateLP** [comment]
I had that problem aswell, but I fixed it, and It should work with fix #16 . Could you put your log at pastebin and post the link here (Saved/Logs/)? Thanks.

**Comment by ninjanody** [comment]
Hello, i had the fix#16 applied but had the same errors. I check the log and one of the errors is that can't find Visual Studio 2013. It is installed but the computed is updated from windows 7 to windows 10.

Here is the log.
[BrickGame.log.txt](https://github.com/AndrewScheidecker/BrickGame/files/166689/BrickGame.log.txt)

**Comment by iUltimateLP** [comment]
Hmm, maybe there is some registry Entry missing during the upgrade.. Try running the setup again and repair the installation.

**Comment by xMeddler** [comment]
Hi. I am also having this issue. I am unsure how to manually rebuild or how to "repair the installation". Do you mean that of UE4? I've been stuck on these issues for several days. Any help would be greatly appreciated!

**Comment by iUltimateLP** [comment]
I meant Visual Studio, try running that setup and select some kind of repair Option!

**Comment by xMeddler** [comment]
I am unsure where to start. How can I combine and run these files? I've only been working with raw code for a couple of months and I'm a bit confused :/ 
![5d24164f53059e0ed1d2c17e31d4b8a8](https://cloud.githubusercontent.com/assets/18039694/14028994/c26e479c-f1bc-11e5-87c0-4f5ebb040d55.png)

**Comment by xMeddler** [comment]
Furthermore, does the "+" indicate this line of code was added to fix issue, OR that I should add a "+" to my copy of the code? 
![](https://i.gyazo.com/3de9168477ade7562b9943d4f3723057.png)

**Comment by iUltimateLP** [comment]
Yep the green line shows what I fixed to make it working, but If you just clone the repo / click on the Download ZIP button on the repo's home page, you should be fine by downloading the whole thing and opening the .uproject. If you want to add it to your project, just copy all folders out of the Plugins folder in your Plugins folder of your project (if it's not there, create it!).

**Comment by xMeddler** [comment]
When I open the .uproject I get these errors: 
![26d6ca82dc75835d6c65fcb246450b70](https://cloud.githubusercontent.com/assets/18039694/14029942/4c765cf4-f1c2-11e5-8026-0ce771d04ad9.png)
![3cf28b9055693e4e89716acea30c1b61](https://cloud.githubusercontent.com/assets/18039694/14029949/50f091c8-f1c2-11e5-82f2-18bfd83a6d23.png)
I am using UE 4.10. 

When I copy the plugin folders into my plugins folder into C:\Program Files\Epic Games\4.10\Engine\Plugins, Enable them within UE4 and restart, I receive this message:
![93ef4447c51d19f293efff9f787979ad](https://cloud.githubusercontent.com/assets/18039694/14030207/b842ca66-f1c3-11e5-9a4c-06b7c95b0cd5.png)

I am unsure how to proceed.

**Comment by iUltimateLP** [comment]
Log file?
Oh it seems like you have the plugins two times in your project?

**Comment by xMeddler** [comment]
1. Where can I find a log file? 
2. There does not appear to be any duplicates in C:\Program Files\Epic Games\4.10\Engine\Plugins

**Comment by iUltimateLP** [comment]
Oh no, not in the engine's plugin folder, in the plugins folder of your project! Delete it out of the engine's plugins folder. The log file is located under /Saved/Logs/name.log

**Comment by xMeddler** [comment]
Thank you! I did not realize it was in the wrong place. Should I create the plugins folder within the first project directory?  e.g. C:\Users\Dustin\Documents\Unreal Projects\BlockExperiments

**Comment by iUltimateLP** [comment]
Yep, if it's not there, create it!

**Comment by xMeddler** [comment]
The plugins now have their own lists in the plugins window (cool!) However after enabling them and restarting, I recieve this error: 
![8af112a461db67eac23884fe8254abd4](https://cloud.githubusercontent.com/assets/18039694/14030712/56c8d7be-f1c6-11e5-9e37-0c680a726557.png)

unsure how to continue.

**Comment by iUltimateLP** [comment]
Hmh, that is strange, never had that. My advice would be to try a fresh start again..

**Comment by xMeddler** [comment]
I un/reinstalled UE4.10, deleted and freshly extracted the brickgame-master rar and was then able to launch the BrickGame.uproject after a successful rebuild. It seems I am still unable to add the plugins to other projects. I'll update this when I get that figured out.

**Comment by AndrewScheidecker** [comment]
I'm going to close this, but please create a new issue if you have trouble using BrickGame with the latest version of the engine.
