### ISSUE TITLE
Emissive glow bock doesn't light up shadows?

### ISSUE THREAD

**Issue by iUltimateLP** [AndrewScheidecker/BrickGame#28]
Title says it all, I tried out to place the emissive blocks under the surface, and it is lit, but it doesn't light up the environment and all the blocks. The shadows / lighting of the block is supplied with AO values as I can remember.. Any chance to get this working? Thank you :3

**Comment by AndrewScheidecker** [comment]
What build of the engine are you using?

**Comment by iUltimateLP** [comment]
Currently using 4.12.3 launcher version, should I try your Unreal branch?

**Comment by AndrewScheidecker** [comment]
Yeah, try [this branch](https://github.com/AndrewScheidecker/UnrealEngine/tree/BrickGame). It's the expected behavior that unmodified UE4 emissive blocks don't light up faces that don't receive ambient/sky lighting.

**Comment by iUltimateLP** [comment]
Will do, i'll report! Thank you!

**Comment by iUltimateLP** [comment]
Yes, lighting caves works now! Thank you!
![image](https://cloud.githubusercontent.com/assets/8491339/16257415/ca610aa6-3858-11e6-9601-ba9230fb4eb0.png)
