### ISSUE TITLE
Cannot open BrickGrid Blueprint

### ISSUE THREAD

**Issue by jnclark1978** [AndrewScheidecker/BrickGame#4]
I have built the custom 4.5.1 and I am using the master BrickGame branch. I registered the custom UE4.5.1 and created project files using it. PIE works fine, but simply double clicking the BrickGrid Blueprint crashes the editor. I read in the forums that this was an issue before you updated the code to 4.5. Is the master not updated? I am not exactly a GitHub master. I donwloaded a Zip from the master branch page, could that be the problem? If not what was the code change required to fix this originally?

**Comment by imbreneyente** [comment]
The BrickGrid blueprint is crashing my editor also. I'm able to open all the other BPs (e.g. BrickGameMode, BrickSaveGame, and the more extensive BP_BrickSkySphere) and play the game in the editor.

I'm using the master branch of BrickGame (last authored on Oct 30, 2014):
https://github.com/AndrewScheidecker/BrickGame
compiled against the modified UE branch "BrickGame-4.5" (last authored on Oct 29, 2014):
https://github.com/AndrewScheidecker/UnrealEngine/tree/BrickGame-4.5
(as described in the readme). The configuration was "Development Editor" for each.

The UE4 Crash Reporter gives:
...
Fatal error: [File:E:\My Documents\GitHub\AndrewScheidecker\UnrealEngine\Engine\Source\Runtime\CoreUObject\Private\Templates\Casts.cpp] [Line: 11] 
Cast of NULL to Package failed
...

Thanks for the project btw. It's quite beautiful.

**Comment by imbreneyente** [comment]
Not really a fix, but if anybody else is having this issue and wants to see (an older version of) the BrickGrid blueprint, I was able to checkout:
https://github.com/AndrewScheidecker/BrickGame/tree/77e3a0b (from Apr 2, 2014)
and compile it against the appropriate UE (4.0.2, unmodified):
https://github.com/EpicGames/UnrealEngine/tree/4.0.2-release

It's not as cool as the master, but everything works.

**Comment by AndrewScheidecker** [comment]
I'm happy to say that I can reproduce this in stock UE 4.5.1, but not in UE4.6.1 or the UE4.7 preview.

**Comment by imbreneyente** [comment]
This is great -- I didn't realize the game would compile against the stock UE 4.6.1. This way everything works and I can view all the current blueprints (including BrickGrid) without any issues. The game doesn't look quite as nice without the lighting modifications and I guess it's missing the performance improvements as well, but at least everything is functional. Thanks!
