### ISSUE TITLE
How to initialize project components

### ISSUE THREAD

**Issue by BloodHound27** [AndrewScheidecker/BrickGame#6]
I am trying to use UBrickGridComponent in my BrickGrid class which is based off of the BrickGrid blueprint.

In my header:
```cpp
TSubobjectPtr<class UBrickGridComponent> BrickGridComp;
```

In the constructor of my source file:
```cpp
BrickGridComp = ObjectInitializer.CreateDefaultSubobject<UBrickGridComponent>(this, TEXT("BrickGridComp"));
```

The project builds the header properly, but throws an error when trying to run the source file. I have other components in my project which compile fine, when using similar syntax. What do you think is the problem? Is there another way to initialize this component?

Error Message:

error LNK2019: unresolved external symbol "private: static class UClass * __cdecl UBrickGridComponent::GetPrivateStaticClass(wchar_t const *)" (?GetPrivateStaticClass@UBrickGridComponent@@CAPEAVUClass@@PEB_W@Z) referenced in function "private: __cdecl ABrickGrid::ABrickGrid(class FObjectInitializer const &)" (??0ABrickGrid@@AEAA@AEBVFObjectInitializer@@@Z)	C:\Users\Ben\Desktop\BrickGame-master\BrickGame-master\Intermediate\ProjectFiles\BrickGrid.cpp.obj

**Comment by BloodHound27** [comment]
I changed the constructor, but still got the same error.

```cpp
ABrickGrid::ABrickGrid(const class FPostConstructInitializeProperties& PCIP)
	: Super(PCIP)
{
	PrimaryActorTick.bCanEverTick = true;
	BrickGridComp = PCIP.CreateDefaultSubobject<UBrickGridComponent>(this, TEXT("BrickGridComp"));
}
```

**Comment by AndrewScheidecker** [comment]
I think this is a case of the UBrickGridComponent definition missing the BRICKGRID_API qualifier. Try changing it to this:
class BRICKGRID_API UBrickGridComponent : public USceneComponent
Let me know if that works and I'll make the change in the master branch.

**Comment by BloodHound27** [comment]
Your instructions worked @AndrewScheidecker! I was beginning to think that I would never sort out that bug.

I put BRICKGRID_API in the right place just as you demonstrated in your reply and removed BRICKGRID_API from the method declarations within the UBrickGridComponent class declaration in the header and now it works perfectly.

Thank you for the help @AndrewScheidecker and happy new year!
